export const Doctor = [
  { value: "Dr. Mick Thompson", label: "Dr. Mick Thompson" },
  { value: "Dr. Sarah Johnson", label: "Dr. Sarah Johnson" },
  { value: "Dr. Emily Carter", label: "Dr. Emily Carter" },
  { value: "Dr. David Lee", label: "Dr. David Lee" },
  { value: "Dr. Anna Kim", label: "Dr. Anna Kim" },
];
export const Designation = [
  { value: "Consultant", label: "Consultant" },
  { value: "Senior Consultant", label: "Senior Consultant" },
  { value: "Specialist", label: "Specialist" },
  { value: "Senior Specialist", label: "Senior Specialist" },
  { value: "Cardiologist", label: "Cardiologist" },
  { value: "Neurologist", label: "Neurologist" },
  { value: "Orthopedic Surgeon", label: "Orthopedic Surgeon" },
  { value: "Pediatrician", label: "Pediatrician" },
  { value: "Gynecologist", label: "Gynecologist" },
  { value: "Obstetrician", label: "Obstetrician" },
  { value: "Psychiatrist", label: "Psychiatrist" },
  { value: "Neurosurgeon", label: "Neurosurgeon" },
  { value: "Oncologist", label: "Oncologist" },
  { value: "Pulmonologist", label: "Pulmonologist" },
  { value: "Urologist", label: "Urologist" },
  { value: "Dermatologist", label: "Dermatologist" },
  { value: "ENT Specialist", label: "ENT Specialist" },
  { value: "Ophthalmologist", label: "Ophthalmologist" },
  { value: "Radiologist", label: "Radiologist" },
  { value: "Anesthesiologist", label: "Anesthesiologist" },
  { value: "Emergency Physician", label: "Emergency Physician" },
  { value: "General Surgeon", label: "General Surgeon" },
  { value: "Internist", label: "Internist" },
  { value: "Nephrologist", label: "Nephrologist" },
  { value: "Gastroenterologist", label: "Gastroenterologist" },
  { value: "Endocrinologist", label: "Endocrinologist" },
  { value: "Rheumatologist", label: "Rheumatologist" },
  { value: "Hematologist", label: "Hematologist" },
  { value: "Infectious Disease Specialist", label: "Infectious Disease Specialist" },
  { value: "Plastic Surgeon", label: "Plastic Surgeon" },
  { value: "Pathologist", label: "Pathologist" },
  { value: "Physiatrist", label: "Physiatrist" },
  { value: "Dentist", label: "Dentist" },
  { value: "Medical Officer", label: "Medical Officer" },
  { value: "Resident Doctor", label: "Resident Doctor" },
  { value: "Junior Resident", label: "Junior Resident" },
  { value: "Senior Resident", label: "Senior Resident" },
  { value: "House Officer", label: "House Officer" }
];
export const Department = [
  { value: "Cardiology", label: "Cardiology" },
  { value: "Neurology", label: "Neurology" },
  { value: "Orthopedics", label: "Orthopedics" },
  { value: "Pediatrics", label: "Pediatrics" },
  { value: "Gynecology", label: "Gynecology" },
  { value: "Obstetrics", label: "Obstetrics" },
  { value: "Psychiatry", label: "Psychiatry" },
  { value: "Neurosurgery", label: "Neurosurgery" },
  { value: "Oncology", label: "Oncology" },
  { value: "Pulmonology", label: "Pulmonology" },
  { value: "Urology", label: "Urology" },
  { value: "Dermatology", label: "Dermatology" },
  { value: "ENT", label: "ENT (Ear, Nose, Throat)" },
  { value: "Ophthalmology", label: "Ophthalmology" },
  { value: "Radiology", label: "Radiology" },
  { value: "Anesthesiology", label: "Anesthesiology" },
  { value: "Emergency Medicine", label: "Emergency Medicine" },
  { value: "General Surgery", label: "General Surgery" },
  { value: "Internal Medicine", label: "Internal Medicine" },
  { value: "Nephrology", label: "Nephrology" },
  { value: "Gastroenterology", label: "Gastroenterology" },
  { value: "Endocrinology", label: "Endocrinology" },
  { value: "Rheumatology", label: "Rheumatology" },
  { value: "Hematology", label: "Hematology" },
  { value: "Infectious Disease", label: "Infectious Disease" },
  { value: "Plastic Surgery", label: "Plastic Surgery" },
  { value: "Pathology", label: "Pathology" },
  { value: "Physical Medicine", label: "Physical Medicine & Rehabilitation" },
  { value: "Dental", label: "Dental" }
];
export const Amount = [
  { value: "$501 - $1000", label: "$501 - $1000" },
  { value: "$501 - $1100", label: "$501 - $1100" },
  { value: "$701 - $1200", label: "$701 - $1200" },
];
export const Status = [
  { value: "Available", label: "Available" },
  { value: "Unavailable", label: "Unavailable" },
];
export const Diagnosis_Type = [
  { value: "Select", label: "Select" },
  { value: "Fever", label: "Fever" },
  { value: "Headache", label: "Headache" },
  { value: "Joint Pain", label: "Joint Pain" },
  { value: "Skin Rash", label: "Skin Rash" },
  { value: "Back Pain", label: "Back Pain" },
];
export const Complaint_History = [
  { value: "Headache", label: "Headache" },
  { value: "Fever", label: "Fever" },
  { value: "Headache", label: "Headache" },
  { value: "Joint Pain", label: "Joint Pain" },
  { value: "Skin Rash", label: "Skin Rash" },
  { value: "Back Pain", label: "Back Pain" },
];
export const Medicine_Name = [
  { value: "Select", label: "Select" },
  { value: "General Medicine", label: "General Medicine" },
  { value: "Axer 90MG Tab", label: "Axer 90MG Tab" },
  { value: "Ramistar XL 2.5", label: "Ramistar XL 2.5" },
];
export const Frequency = [
  { value: "Select", label: "Select" },
  { value: "0-0-1", label: "0-0-1" },
  { value: "1-0-0", label: "1-0-0" },
  { value: "0-1-0", label: "0-1-0" },
];
export const Timing = [
  { value: "Select", label: "Select" },
  { value: "Before Meal", label: "Before Meal" },
  { value: "After Meal", label: "After Meal" },
];
export const empty_Stomach = [
  { value: "Select", label: "Select" },
  { value: "Yes", label: "Yes" },
  { value: "No", label: "No" },
];
export const Service = [
  { value: "Select", label: "Select" },
  { value: "General Consultation", label: "General Consultation" },
  { value: "Dental Cleaning", label: "Dental Cleaning" },
  { value: "Eye Checkup", label: "Eye Checkup" },
  { value: "Blood Test", label: "Blood Test" },
  { value: "Skin Allergy Test", label: "Skin Allergy Test" },
];
export const Payment_Mode = [
  { value: "Select", label: "Select" },
  { value: "Paypal", label: "Paypal" },
  { value: "Stripe", label: "Stripe" },
];
export const Recures_Every = [
  { value: "Select", label: "Select" },
  { value: "1 Week", label: "1 Week" },
  { value: "1 Month", label: "1 Month" },
];
export const Session = [
  { value: "Select", label: "Select" },
  { value: "Morning", label: "Morning" },
  { value: "Afternoon", label: "Noon" },
  { value: "Evening", label: "Evening" },
  { value: "Night", label: "Night" }
];
export const Location = [{ value: "Select", label: "Select" }];
export const Country = [
  { value: "Select", label: "Select" },
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Albania", label: "Albania" },
  { value: "Algeria", label: "Algeria" },
  { value: "Andorra", label: "Andorra" },
  { value: "Angola", label: "Angola" },
  { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
  { value: "Argentina", label: "Argentina" },
  { value: "Armenia", label: "Armenia" },
  { value: "Australia", label: "Australia" },
  { value: "Austria", label: "Austria" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Barbados", label: "Barbados" },
  { value: "Belarus", label: "Belarus" },
  { value: "Belgium", label: "Belgium" },
  { value: "Belize", label: "Belize" },
  { value: "Benin", label: "Benin" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
  { value: "Botswana", label: "Botswana" },
  { value: "Brazil", label: "Brazil" },
  { value: "Brunei", label: "Brunei" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Burundi", label: "Burundi" },
  { value: "Cabo Verde", label: "Cabo Verde" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "Canada", label: "Canada" },
  { value: "Central African Republic", label: "Central African Republic" },
  { value: "Chad", label: "Chad" },
  { value: "Chile", label: "Chile" },
  { value: "China", label: "China" },
  { value: "Colombia", label: "Colombia" },
  { value: "Comoros", label: "Comoros" },
  { value: "Congo (Congo-Brazzaville)", label: "Congo (Congo-Brazzaville)" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Croatia", label: "Croatia" },
  { value: "Cuba", label: "Cuba" },
  { value: "Cyprus", label: "Cyprus" },
  { value: "Czech Republic", label: "Czech Republic" },
  { value: "Democratic Republic of the Congo", label: "Democratic Republic of the Congo" },
  { value: "Denmark", label: "Denmark" },
  { value: "Djibouti", label: "Djibouti" },
  { value: "Dominica", label: "Dominica" },
  { value: "Dominican Republic", label: "Dominican Republic" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Egypt", label: "Egypt" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea" },
  { value: "Eritrea", label: "Eritrea" },
  { value: "Estonia", label: "Estonia" },
  { value: "Eswatini", label: "Eswatini" },
  { value: "Ethiopia", label: "Ethiopia" },
  { value: "Fiji", label: "Fiji" },
  { value: "Finland", label: "Finland" },
  { value: "France", label: "France" },
  { value: "Gabon", label: "Gabon" },
  { value: "Gambia", label: "Gambia" },
  { value: "Georgia", label: "Georgia" },
  { value: "Germany", label: "Germany" },
  { value: "Ghana", label: "Ghana" },
  { value: "Greece", label: "Greece" },
  { value: "Grenada", label: "Grenada" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Guinea", label: "Guinea" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau" },
  { value: "Guyana", label: "Guyana" },
  { value: "Haiti", label: "Haiti" },
  { value: "Honduras", label: "Honduras" },
  { value: "Hungary", label: "Hungary" },
  { value: "Iceland", label: "Iceland" },
  { value: "India", label: "India" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Iran", label: "Iran" },
  { value: "Iraq", label: "Iraq" },
  { value: "Ireland", label: "Ireland" },
  { value: "Israel", label: "Israel" },
  { value: "Italy", label: "Italy" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Japan", label: "Japan" },
  { value: "Jordan", label: "Jordan" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  { value: "Kenya", label: "Kenya" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { value: "Laos", label: "Laos" },
  { value: "Latvia", label: "Latvia" },
  { value: "Lebanon", label: "Lebanon" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Liberia", label: "Liberia" },
  { value: "Libya", label: "Libya" },
  { value: "Liechtenstein", label: "Liechtenstein" },
  { value: "Lithuania", label: "Lithuania" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Madagascar", label: "Madagascar" },
  { value: "Malawi", label: "Malawi" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Maldives", label: "Maldives" },
  { value: "Mali", label: "Mali" },
  { value: "Malta", label: "Malta" },
  { value: "Marshall Islands", label: "Marshall Islands" },
  { value: "Mauritania", label: "Mauritania" },
  { value: "Mauritius", label: "Mauritius" },
  { value: "Mexico", label: "Mexico" },
  { value: "Micronesia", label: "Micronesia" },
  { value: "Moldova", label: "Moldova" },
  { value: "Monaco", label: "Monaco" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "Montenegro", label: "Montenegro" },
  { value: "Morocco", label: "Morocco" },
  { value: "Mozambique", label: "Mozambique" },
  { value: "Myanmar", label: "Myanmar" },
  { value: "Namibia", label: "Namibia" },
  { value: "Nauru", label: "Nauru" },
  { value: "Nepal", label: "Nepal" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Niger", label: "Niger" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "North Korea", label: "North Korea" },
  { value: "North Macedonia", label: "North Macedonia" },
  { value: "Norway", label: "Norway" },
  { value: "Oman", label: "Oman" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Palau", label: "Palau" },
  { value: "Panama", label: "Panama" },
  { value: "Papua New Guinea", label: "Papua New Guinea" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Peru", label: "Peru" },
  { value: "Philippines", label: "Philippines" },
  { value: "Poland", label: "Poland" },
  { value: "Portugal", label: "Portugal" },
  { value: "Qatar", label: "Qatar" },
  { value: "Romania", label: "Romania" },
  { value: "Russia", label: "Russia" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
  { value: "Saint Lucia", label: "Saint Lucia" },
  { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
  { value: "Samoa", label: "Samoa" },
  { value: "San Marino", label: "San Marino" },
  { value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Senegal", label: "Senegal" },
  { value: "Serbia", label: "Serbia" },
  { value: "Seychelles", label: "Seychelles" },
  { value: "Sierra Leone", label: "Sierra Leone" },
  { value: "Singapore", label: "Singapore" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Slovenia", label: "Slovenia" },
  { value: "Solomon Islands", label: "Solomon Islands" },
  { value: "Somalia", label: "Somalia" },
  { value: "South Africa", label: "South Africa" },
  { value: "South Korea", label: "South Korea" },
  { value: "South Sudan", label: "South Sudan" },
  { value: "Spain", label: "Spain" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Sudan", label: "Sudan" },
  { value: "Suriname", label: "Suriname" },
  { value: "Sweden", label: "Sweden" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Syria", label: "Syria" },
  { value: "Taiwan", label: "Taiwan" },
  { value: "Tajikistan", label: "Tajikistan" },
  { value: "Tanzania", label: "Tanzania" },
  { value: "Thailand", label: "Thailand" },
  { value: "Timor-Leste", label: "Timor-Leste" },
  { value: "Togo", label: "Togo" },
  { value: "Tonga", label: "Tonga" },
  { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
  { value: "Tunisia", label: "Tunisia" },
  { value: "Turkey", label: "Turkey" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "Tuvalu", label: "Tuvalu" },
  { value: "Uganda", label: "Uganda" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "United Kingdom", label: "United Kingdom" },
  { value: "United States", label: "United States" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Uzbekistan", label: "Uzbekistan" },
  { value: "Vanuatu", label: "Vanuatu" },
  { value: "Vatican City", label: "Vatican City" },
  { value: "Venezuela", label: "Venezuela" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Yemen", label: "Yemen" },
  { value: "Zambia", label: "Zambia" },
  { value: "Zimbabwe", label: "Zimbabwe" }
];
export const State = [
  { value: "Select", label: "Select" },
  { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  { value: "Assam", label: "Assam" },
  { value: "Bihar", label: "Bihar" },
  { value: "Chhattisgarh", label: "Chhattisgarh" },
  { value: "Goa", label: "Goa" },
  { value: "Gujarat", label: "Gujarat" },
  { value: "Haryana", label: "Haryana" },
  { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  { value: "Jharkhand", label: "Jharkhand" },
  { value: "Karnataka", label: "Karnataka" },
  { value: "Kerala", label: "Kerala" },
  { value: "Madhya Pradesh", label: "Madhya Pradesh" },
  { value: "Maharashtra", label: "Maharashtra" },
  { value: "Manipur", label: "Manipur" },
  { value: "Meghalaya", label: "Meghalaya" },
  { value: "Mizoram", label: "Mizoram" },
  { value: "Nagaland", label: "Nagaland" },
  { value: "Odisha", label: "Odisha" },
  { value: "Punjab", label: "Punjab" },
  { value: "Rajasthan", label: "Rajasthan" },
  { value: "Sikkim", label: "Sikkim" },
  { value: "Tamil Nadu", label: "Tamil Nadu" },
  { value: "Telangana", label: "Telangana" },
  { value: "Tripura", label: "Tripura" },
  { value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { value: "Uttarakhand", label: "Uttarakhand" },
  { value: "West Bengal", label: "West Bengal" },
  { value: "Delhi", label: "Delhi" },
  { value: "Puducherry", label: "Puducherry" },
  { value: "Chandigarh", label: "Chandigarh" },
  { value: "Jammu and Kashmir", label: "Jammu and Kashmir" },
  { value: "Ladakh", label: "Ladakh" }
];
export const City = [
  { value: "Select", label: "Select" },
  { value: "Mumbai", label: "Mumbai" },
  { value: "Delhi", label: "Delhi" },
  { value: "Bangalore", label: "Bangalore" },
  { value: "Hyderabad", label: "Hyderabad" },
  { value: "Ahmedabad", label: "Ahmedabad" },
  { value: "Chennai", label: "Chennai" },
  { value: "Kolkata", label: "Kolkata" },
  { value: "Pune", label: "Pune" },
  { value: "Jaipur", label: "Jaipur" },
  { value: "Surat", label: "Surat" },
  { value: "Lucknow", label: "Lucknow" },
  { value: "Kanpur", label: "Kanpur" },
  { value: "Nagpur", label: "Nagpur" },
  { value: "Indore", label: "Indore" },
  { value: "Thane", label: "Thane" },
  { value: "Bhopal", label: "Bhopal" },
  { value: "Visakhapatnam", label: "Visakhapatnam" },
  { value: "Pimpri-Chinchwad", label: "Pimpri-Chinchwad" },
  { value: "Patna", label: "Patna" },
  { value: "Vadodara", label: "Vadodara" },
  { value: "Ghaziabad", label: "Ghaziabad" },
  { value: "Ludhiana", label: "Ludhiana" },
  { value: "Agra", label: "Agra" },
  { value: "Nashik", label: "Nashik" },
  { value: "Faridabad", label: "Faridabad" },
  { value: "Meerut", label: "Meerut" },
  { value: "Rajkot", label: "Rajkot" },
  { value: "Kalyan-Dombivali", label: "Kalyan-Dombivali" },
  { value: "Vasai-Virar", label: "Vasai-Virar" },
  { value: "Varanasi", label: "Varanasi" },
  { value: "Srinagar", label: "Srinagar" },
  { value: "Aurangabad", label: "Aurangabad" },
  { value: "Dhanbad", label: "Dhanbad" },
  { value: "Amritsar", label: "Amritsar" },
  { value: "Navi Mumbai", label: "Navi Mumbai" },
  { value: "Allahabad", label: "Allahabad" },
  { value: "Ranchi", label: "Ranchi" },
  { value: "Howrah", label: "Howrah" },
  { value: "Coimbatore", label: "Coimbatore" },
  { value: "Jabalpur", label: "Jabalpur" },
  { value: "Gwalior", label: "Gwalior" },
  { value: "Vijayawada", label: "Vijayawada" },
  { value: "Jodhpur", label: "Jodhpur" },
  { value: "Madurai", label: "Madurai" },
  { value: "Raipur", label: "Raipur" },
  { value: "Kota", label: "Kota" },
  { value: "Chandigarh", label: "Chandigarh" },
  { value: "Guwahati", label: "Guwahati" },
  { value: "Solapur", label: "Solapur" },
  { value: "Hubli-Dharwad", label: "Hubli-Dharwad" },
  { value: "Mysore", label: "Mysore" },
  { value: "Tiruchirappalli", label: "Tiruchirappalli" },
  { value: "Bareilly", label: "Bareilly" },
  { value: "Aligarh", label: "Aligarh" },
  { value: "Tiruppur", label: "Tiruppur" },
  { value: "Moradabad", label: "Moradabad" },
  { value: "Jalandhar", label: "Jalandhar" },
  { value: "Bhubaneswar", label: "Bhubaneswar" },
  { value: "Salem", label: "Salem" },
  { value: "Warangal", label: "Warangal" },
  { value: "Guntur", label: "Guntur" },
  { value: "Bhiwandi", label: "Bhiwandi" },
  { value: "Saharanpur", label: "Saharanpur" },
  { value: "Gorakhpur", label: "Gorakhpur" },
  { value: "Bikaner", label: "Bikaner" },
  { value: "Amravati", label: "Amravati" },
  { value: "Noida", label: "Noida" },
  { value: "Jamshedpur", label: "Jamshedpur" },
  { value: "Bhilai", label: "Bhilai" },
  { value: "Cuttack", label: "Cuttack" },
  { value: "Firozabad", label: "Firozabad" },
  { value: "Kochi", label: "Kochi" },
  { value: "Nellore", label: "Nellore" },
  { value: "Bhavnagar", label: "Bhavnagar" },
  { value: "Dehradun", label: "Dehradun" },
  { value: "Durgapur", label: "Durgapur" },
  { value: "Asansol", label: "Asansol" },
  { value: "Rourkela", label: "Rourkela" },
  { value: "Nanded", label: "Nanded" },
  { value: "Kolhapur", label: "Kolhapur" },
  { value: "Ajmer", label: "Ajmer" },
  { value: "Akola", label: "Akola" },
  { value: "Gulbarga", label: "Gulbarga" },
  { value: "Jamnagar", label: "Jamnagar" },
  { value: "Ujjain", label: "Ujjain" },
  { value: "Loni", label: "Loni" },
  { value: "Siliguri", label: "Siliguri" },
  { value: "Jhansi", label: "Jhansi" },
  { value: "Ulhasnagar", label: "Ulhasnagar" },
  { value: "Jammu", label: "Jammu" },
  { value: "Mangalore", label: "Mangalore" },
  { value: "Erode", label: "Erode" },
  { value: "Belgaum", label: "Belgaum" },
  { value: "Ambattur", label: "Ambattur" },
  { value: "Tirunelveli", label: "Tirunelveli" },
  { value: "Malegaon", label: "Malegaon" },
  { value: "Gaya", label: "Gaya" },
  { value: "Jalgaon", label: "Jalgaon" },
  { value: "Udaipur", label: "Udaipur" },
  { value: "Maheshtala", label: "Maheshtala" }
];
export const StatusActive = [
  { value: "Select", label: "Select" },
  { value: "Active", label: "Active" },
  { value: "Inactive", label: "Inactive" },
];
export const contactType = [
  { value: "1", label: "Select" },
  { value: "2", label: "Admin" },
  { value: "3", label: "Stock Out" },
];
export const notesOptions1 = [
  { value: "Bulk Actions", label: "Bulk Actions" },
  { value: "Delete Marked", label: "Delete Marked" },
  { value: "Unmark All", label: "Unmark All" },
  { value: "Mark All", label: "Mark All" },
];
export const notesOptions2 = [
  { value: "Recent", label: "Recent" },
  { value: "Last Modified", label: "Last Modified" },
  { value: "Last Modified by me", label: "Last Modified by me" },
];
export const Assignee = [
  { value: "1", label: "Select" },
  { value: "2", label: "Kathleen" },
  { value: "3", label: "Gifford" },
];
export const Priority = [
  { value: "1", label: "Select" },
  { value: "2", label: "Medium" },
  { value: "3", label: "High" },
  { value: "4", label: "Low" },
];
export const tag = [
  { value: "Select", label: "Select" },
  { value: "Internal", label: "Internal" },
  { value: "Projects", label: "Projects" },
  { value: "Meetings", label: "Meetings" },
  { value: "Reminder", label: "Reminder" },
];

export const priority = [
  { value: "Select", label: "Select" },
  { value: "Medium", label: "Medium" },
  { value: "High", label: "High" },
  { value: "Low", label: "Low" },
];
export const addAssignee = [
  { value: "Select", label: "Select" },
  { value: "Sophie", label: "Sophie" },
  { value: "Cameron", label: "Cameron" },
  { value: "Doris", label: "Doris" },
  { value: "Rufana", label: "Rufana" },
];
export const StatusCompleted = [
  { value: "Select", label: "Select" },
  { value: "Completed", label: "Completed" },
  { value: "Pending", label: "Pending" },
  { value: "Onhold", label: "Onhold" },
  { value: "Inprogress", label: "Inprogress" },
];
export const Blood_Group = [
  { value: "Select", label: "Select" },
  { value: "AB+", label: "AB+" },
  { value: "AB-", label: "AB-" },
  { value: "O+", label: "O+" },
  { value: "O-", label: "O-" },
  { value: "A+", label: "A+" },
  { value: "A-", label: "A-" },
  { value: "B+", label: "B+" },
  { value: "B-", label: "B-" },
];
export const Gender = [
  { value: "Select", label: "Select" },
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
  { value: "Others", label: "Others" },
];
export const Appointment_Type = [
  { value: "Select", label: "Select" },
  { value: "Online Consultation", label: "Online Consultation" },
  { value: "In-Person Visit", label: "In-Person Visit" },
  { value: "Emergency", label: "Emergency" },
  { value: "Follow-up", label: "Follow-up" }
];
export const Primary_Doctor = [
  { value: "Select", label: "Select" },
  { value: "Dr. Mick Thompson", label: "Dr. Mick Thompson" },
  { value: "Dr. Sarah Johnson", label: "Dr. Sarah Johnson" },
  { value: "Dr. Emily Carter", label: "Dr. Emily Carter" },
  { value: "Dr. David Lee", label: "Dr. David Lee" },
  { value: "Dr. Anna Kim", label: "Dr. Anna Kim" },
  { value: "Dr. John Smith", label: "Dr. John Smith" },
  { value: "Dr. Lisa White", label: "Dr. Lisa White" },
  { value: "Dr. Patrica Brown", label: "Dr. Patrica Brown" },
];
export const Bulk_Action = [
  { value: "Select", label: "Select" },
  { value: "Bulk Actions", label: "Bulk Actions" },
  { value: "Delete Marked", label: "Delete Marked" },
  { value: "Unmark All", label: "Unmark All" },
  { value: "Mark All", label: "Mark All" },
];
export const Recent = [
  { value: "Select", label: "Select" },
  { value: "Last Modified", label: "Last Modified" },
  { value: "Last Modified by me", label: "Last Modified by me" },
];
export const defaultSingle = [
  { value: "1", label: "This is a placeholder" },
  { value: "2", label: "Choice 1" },
  { value: "3", label: "Choice 2" },
  { value: "4", label: "Choice 3" },
];
export const Timezone = [
  { value: "(+5:30) GMT", label: "(+5:30) GMT" },
  { value: "(GMT -10:00) Hawaii", label: "(GMT -10:00) Hawaii" },
  { value: "(GMT -9:30) Taiohae", label: "(GMT -9:30) Taiohae" },
  { value: "(GMT -9:00) Alaska ", label: "(GMT -9:00) Alaska " },
  {
    value: "(GMT -8:00) Pacific Time, Canada",
    label: "(GMT -8:00) Pacific Time, Canada",
  },
];
export const Start_Week = [
  { value: "Monday", label: "Monday" },
  { value: "Tuesday", label: "Tuesday" },
  { value: "Wednesday", label: "Wednesday" },
  { value: "Thursday", label: "Thursday" },
  { value: "Friday", label: "Friday" },
  { value: "Saturday", label: "Saturday" },
  { value: "Sunday", label: "Sunday" },
];
export const Date_Format = [
  { value: "18 Mar 2025", label: "18 Mar 2025" },
  { value: "Mar 18 2025", label: "Mar 18 2025" },
  { value: "2025 Mar 18", label: "2025 Mar 18" },
];
export const Time_Format = [
  { value: "12 hrs", label: "12 hrs" },
  { value: "24hrs", label: "24hrs" },
];
export const Default_Language = [
  { value: "English", label: "English" },
  { value: "German", label: "German" },
  { value: "Arabic", label: "Arabic" },
  { value: "French", label: "French" },
];
export const Currency = [
  { value: "USD", label: "USD" },
  { value: "Dollar", label: "Dollar" },
  { value: "Euro", label: "Euro" },
  { value: "Pound", label: "Pound" },
  { value: "Rupee", label: "Rupee" },
];
export const Currency_Symbol = [
  { value: "$", label: "$" },
  { value: "₹", label: "₹" },
  { value: "£", label: "£" },
  { value: "€", label: "€" },
];
export const Currency_Position = [
  { value: "$100", label: "$100" },
  { value: "100$", label: "100$" },
  { value: "$ 100", label: "$ 100" },
  { value: "100 $", label: "100 $" },
];
export const Decimal_Seperator = [
  { value: ".", label: "." },
  { value: ",", label: "," },
];
export const Thousand_Seperator = [
  { value: ".", label: "." },
  { value: ",", label: "," },
];
export const Reminder = [
  { value: "Email", label: "Email" },
  { value: "SMS", label: "SMS" },
];
export const Welcome_Email = [
  { value: "Select", label: "Select" },
  { value: "Welcome Email", label: "Welcome Email" },
  { value: "Appointment Reminder", label: "Appointment Reminder" },
  { value: "Appointment Confirmation", label: "Appointment Confirmation" },
  { value: "Appointment Rescheduled", label: "Appointment Rescheduled" },
  { value: "Appointment Cancelled", label: "Appointment Cancelled" },
  { value: "Test Result Notification", label: "Test Result Notification" },
];
export const days = [
  { value: "01", label: "01" },
  { value: "02", label: "02" },
  { value: "03", label: "03" },
  { value: "05", label: "05" },
  { value: "10", label: "10" },
];
export const SMS_Reminder = [
  { value: "Select", label: "Select" },
  { value: "Appointment Confirmation", label: "Appointment Confirmation" },
  { value: "Appointment Reminder", label: "Appointment Reminder" },
  { value: "Appointment Rescheduled", label: "Appointment Rescheduled" },
  { value: "Appointment Cancellation", label: "Appointment Cancellation" },
  { value: "Test Results Notification", label: "Test Results Notification" },
  { value: "Follow-Up Reminder", label: "Follow-Up Reminder" },
];
export const Email_Reminder = [
  { value: "Select", label: "Select" },
  { value: "Welcome Email", label: "Welcome Email" },
  { value: "Appointment Reminder", label: "Appointment Reminder" },
  { value: "Appointment Rescheduled", label: "Appointment Rescheduled" },
  { value: "Appointment Cancellation", label: "Appointment Cancellation" },
  { value: "Test Results Notification", label: "Test Results Notification" },
];
export const Lunch_Break = [
  { value: "Select", label: "Select" },
  { value: "15 Mins", label: "15 Mins" },
  { value: "30 Mins", label: "30 Mins" },
  { value: "45 Mins", label: "45 Mins" },
  { value: "60 Mins", label: "60 Mins" },
];
export const Lunch_at = [
  { value: "Select", label: "Select" },
  { value: "11 AM", label: "11 AM" },
  { value: "01:00 PM", label: "01:00 PM" },
  { value: "05:00 PM", label: "05:00 PM" },
];
export const Invoice_Roundoff = [
  { value: "Select", label: "Select" },
  { value: "Mar 18 2025", label: "Mar 18 2025" },
  { value: "2025 Mar 18", label: "2025 Mar 18" },
];
export const Module = [
  { value: "Select", label: "Select" },
  { value: "Patient", label: "Patient" },
  { value: "Staff", label: "Staff" },
];
export const Input_Type = [
  { value: "Select", label: "Select" },
  { value: "Text", label: "Text" },
  { value: "Number", label: "Number" },
  { value: "Password", label: "Password" },
  { value: "File", label: "File" },
];
export const Cookies_Position = [
  { value: "Select", label: "Select" },
  { value: "Select", label: "Select" },
];

export const TicketStatus = [
  { value: "Select", label: "Select" },
  { value: "Inprogress", label: "Inprogress" },
  { value: "Resolved", label: "Resolved" },
  { value: "Closed", label: "Closed" },
  { value: "open", label: "open" },
];
export const StaffsRole = [
  { value: "Select", label: "Select" },
  { value: "Admin", label: "Admin" },
  { value: "Reception", label: "Reception" },
  { value: "Nurse", label: "Nurse" },
  { value: "Nurse Practitioner", label: "Nurse Practitioner" },
];
export const StaffsDesignation = [
  { value: "Select", label: "Select" },
  { value: "Admin Officer", label: "Admin Officer" },
  { value: "Front Officer", label: "Front Officer" },
  { value: "Medical Recorder", label: "Medical Recorder" },
  { value: "Billing Executive", label: "Billing Executive" },
];
export const DesignDepartment = [
  { value: "Select", label: "Select" },
  { value: "Nurse", label: "Nurse" },
  { value: "Pharmacist", label: "Pharmacist" },
  { value: "Receptionist", label: "Receptionist" },
  { value: "Technician", label: "Technician" },
  { value: "Medical Assistant", label: "Medical Assistant" },
];
export const Employee = [
  { value: "Select", label: "Select" },
  { value: "James Adair", label: "James Adair" },
  { value: "Adam Milne", label: "Adam Milne" },
  { value: "Richard Clark", label: "Richard Clark" },
  { value: "Robert Reid", label: "Robert Reid" },
];
export const LeaveType = [
  { value: "Select", label: "Select" },
  { value: "Sick Leave", label: "Sick Leave" },
  { value: "Casual Leave", label: "Casual Leave" },
  { value: "Emergency", label: "Emergency" },
  { value: "Vacation", label: "Vacation" },
];
export const Datetype = [
  { value: "Select", label: "Select" },
  { value: "Full Day", label: "Full Day" },
  { value: "Half Day", label: "Half Day" },
];
export const Staff = [
  { value: "Select", label: "Select" },
  { value: "Select staff", label: "Select staff" },
];
export const Received_From = [
  { value: "Select", label: "Select" },
  { value: "Alberto Ripley", label: "Alberto Ripley" },
  { value: "Susan Babin", label: "Susan Babin" },
  { value: "Martin Lisa", label: "Martin Lisa" },
  { value: "Stella Mary", label: "Stella Mary" },
  { value: "Carol Lam", label: "Carol Lam" },
];
export const Category = [
  { value: "Select", label: "Select" },
  { value: "Medical Supplies", label: "Medical Supplies" },
  { value: "Laboratory", label: "Laboratory" },
  { value: "Medical Supplies", label: "Medical Supplies" },
  { value: "Cleaning Services", label: "Cleaning Services" },
];
export const Purchased_By = [
  { value: "Select", label: "Select" },
  { value: "James Allaire", label: "James Allaire" },
  { value: "Esther Schmidt", label: "Esther Schmidt" },
  { value: "Judi Lenahan", label: "Judi Lenahan" },
  { value: "Robert Reid", label: "Robert Reid" },
];
export const Patient = [
  { value: "Select", label: "Select" },
  { value: "Alberto Ripley", label: "Alberto Ripley" },
  { value: "Susan Babin", label: "Susan Babin" },
  { value: "Martin Lisa", label: "Martin Lisa" },
  { value: "Stella Mary", label: "Stella Mary" },
  { value: "Carol Lam", label: "Carol Lam" },
  { value: "Jesus Adams", label: "Jesus Adams" },
  { value: "Ezra Belcher", label: "Ezra Belcher" },
];
export const Practioner = [
  { value: "Select", label: "Select" },
  { value: "Dr. Mick Thompson", label: "Dr. Mick Thompson" },
  { value: "Dr. Sarah Johnson", label: "Dr. Sarah Johnson" },
  { value: "Dr. Emily Carter", label: "Dr. Emily Carter" },
  { value: "Dr. David Lee", label: "Dr. David Lee" },
  { value: "Dr. Anna Kim", label: "Dr. Anna Kim" },
  { value: "Dr. John Smith", label: "Dr. John Smith" },
  { value: "Dr. Lisa White", label: "Dr. Lisa White" },
  { value: "Dr. Patrica Brown", label: "Dr. Patrica Brown" },
];
export const Country_Code = [
  { value: "Select", label: "Select" },
  { value: "US", label: "US" },
  { value: "CA", label: "CA" },
  { value: "UK", label: "UK" },
  { value: "DE", label: "DE" },
  { value: "FR", label: "FR" },
];
export const Country_Name = [
  { value: "Select", label: "Select" },
  { value: "USA", label: "USA" },
  { value: "Canada", label: "Canada" },
  { value: "UK", label: "UK" },
  { value: "Germany", label: "Germany" },
  { value: "France", label: "France" },
];
export const Status_Checkout = [
  { value: "Select", label: "Select" },
  { value: "Checked Out", label: "Checked Out" },
  { value: "Checked In", label: "Checked In" },
  { value: "Cancelled", label: "Cancelled" },
  { value: "Schedule", label: "Schedule" },
  { value: "Confirmed", label: "Confirmed" },
];
export const Location_Type = [
  { value: "Select", label: "Select" },
  { value: "In Person", label: "In Person" },
  { value: "Video Consultation", label: "Video Consultation" },
  { value: "Both", label: "Both" },
];
export const Supplier = [
  { value: "Select", label: "Select" },
  { value: "New one", label: "New one" },
  { value: "Old one", label: "Old one" },
  { value: "Recent one", label: "Recent one" },
];
export const Condition = [
  { value: "Select", label: "Select" },
  { value: "Good one", label: "Good one" },
  { value: "Old one", label: "Old one" },
  { value: "Recent one", label: "Recent one" },
];
export const StatusApproved = [
  { value: "Select", label: "Select" },
  { value: "Approved", label: "Approved" },
  { value: "Pending", label: "Pending" },
];
export const Discount = [
  { value: "0%", label: "0%" },
  { value: "1%", label: "1%" },
  { value: "2%", label: "2%" },
  { value: "3%", label: "3%" },
  { value: "4%", label: "4%" },
];
export const Service_Name = [
  { value: "General Consultation", label: "General Consultation" },
  { value: "Dental Cleaning", label: "Dental Cleaning" },
  { value: "Eye Checkup", label: "Eye Checkup" },
  { value: "X-Ray", label: "X-Ray" },
  { value: "Physiotherapy Session", label: "Physiotherapy Session" },
];
export const Specialization = [
  { value: "General Medicine", label: "General Medicine" },
  { value: "Dentistry", label: "Dentistry" },
  { value: "Ophthalmology", label: "Ophthalmology" },
  { value: "Radiology", label: "Radiology" },
  { value: "Physiotherapy", label: "Physiotherapy" },
];


